### ISSUE TITLE
Hi, a few questions

### ISSUE THREAD

**Issue by zarEclEC** [alissonlauffer/Customgram#1]
Is this client an alternative?
Which features does it have?
Where can I download it?

**Comment by alissonlauffer** [comment]
1. Yes, it is.
2. It has some basic features (because I don't like bloated clients):
  - Option to set up a proxy before login.
  - Option to clear media from cache.
  - "Delete for everyone" enabled by default.
  - Upload dates for profile photos.
3. For now, you can download apks from https://t.me/Customgram. I have plans of submitting it to the Play Store, but I don't have a developer account yet.

If you would like to contribute to my client, contributions are welcome.

**Comment by zarEclEC** [comment]
Thanks for your answers. I'm currently studying for my exams, but I'll be doing something for this repo in the future, when I'll have the time.

**Comment by zarEclEC** [comment]
May I suggest you to put those answes in the readme?

**Comment by alissonlauffer** [comment]
> May I suggest you to put those answes in the readme?

Yeah, the readme will be updated later.
